apps/tickets/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    # path('',                            views.index,                     name='index'),
    path('ticket/',                     views.Tickets.as_view(),         name='tickets'),
    path('ticket/create/',              views.TicketCreate.as_view(),    name='ticket-create'),
    path('ticket/update/<int:pk>/',     views.TicketUpdate.as_view(),    name='ticket-update'),
    path('ticket/<int:pk>/delete/',     views.TicketDelete.as_view(),    name='ticket-delete'),
    path('ticket/gestion/',             views.TicketGestion.as_view(),   name='gestion'),
    path('ticket/observacion/',         views.TicketObservacion.as_view(), name='observacion'),
    path('ticket/ver/',                 views.TicketVer.as_view(),       name='ticket-ver'),
    path('pdf/',                        views.GeneratePDF.as_view(),     name='ver-pdf' ),
    # path('<int:id>/modificar/',views.TicketModificar.as_view(), name='edit-ticket'),
    # path('<int:id>/ver',       views.TicketVer.as_view(), name='ver-ticket'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.admin2.urls')),
    path('', include('apps.contactos.urls')),
    path('', include('apps.tickets.urls')),
    path('', include('apps.campeonato.urls')),
    path('', include('apps.evento.urls')),
]

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tickets/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.
# class Role(models.Model):
#     nombre = models.CharField(max_length=32)
#     descripcion = models.CharField(max_length=256, blank=True)
#     administracion = models.BooleanField(default=False)
#     parametros = models.BooleanField(default=False)
#     casos = models.BooleanField(default=False)
#     class Meta(object):
#         ordering = ['nombre']
#         verbose_name = 'role'
#         verbose_name_plural = 'roles'
#
#     def __str__(self):
#         return str(self.nombre)
#===============================================================================
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, primary_key=True)
    telefono = models.CharField(max_length=64, blank=True, default='')
    # role = models.ForeignKey(Role, on_delete=models.PROTECT, null=True)

    def __str__(self):
        ordering = ['user']
        return str(self.user.username)
#===============================================================================
class EstadoTicket(models.Model):
    id = models.CharField(primary_key=True, max_length=16)
    nombre = models.CharField(max_length=32)
    color = models.CharField(max_length=32)
    descripcion = models.CharField(max_length=256, blank=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'estado - caso'
        verbose_name_plural = 'estados - caso'

    def __str__(self):
        return str(self.nombre)

#===============================================================================
class TipoUrgencia(models.Model):
    id = models.CharField(primary_key=True, max_length=16)
    nombre = models.CharField(max_length=32)
    tiempo_solucion = models.IntegerField(default=1, help_text="Tiempo en Minutos")
    descripcion = models.CharField(max_length=256, blank=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'tipo - urgencia'
        verbose_name_plural = 'tipo - urgencias'

    def __str__(self):
        return str(self.nombre)
#===============================================================================

class Ticket(models.Model):
    nombre = models.CharField(max_length=64)
    urgencia = models.ForeignKey(TipoUrgencia, on_delete=models.PROTECT)
    descripcion = models.TextField(max_length=1024, blank=True)
    solicitante = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, related_name='solicitante')
    notas = models.TextField(max_length=1024, blank=True)
    responsable = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, related_name='responsable')
    solucion = models.TextField(max_length=1024, blank=True)
    estado = models.ForeignKey(EstadoTicket,blank=True, null=True, on_delete=models.PROTECT)
    retroalimentacion = models.TextField(max_length=1024, blank=True)
    f_inicio = models.DateTimeField(verbose_name='fecha_inicio', blank=True, null=True)
    f_fin = models.DateTimeField(verbose_name='fecha fin', blank=True, null=True)
    f_registro = models.DateTimeField(verbose_name="fecha registro", auto_now_add=True,)
    evaluacion_cliente = models.BigIntegerField(blank=True,null=True)

    class Meta:
        ordering = ['-pk']
        verbose_name = 'Ticket'
        verbose_name_plural = 'Tickets'

    def __str__(self):
        return str(self.pk)

#===============================================================================
class AuditoriaTicketEstado(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.PROTECT)
    estado = models.ForeignKey(EstadoTicket, on_delete=models.PROTECT)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name='usuario_cambio')
    usuario_responsable = models.ForeignKey(User, on_delete=models.PROTECT, null=True ,related_name='usuario_responsable')
    observaciones = models.CharField(max_length=1024, blank=True)
    f_registro = models.DateTimeField(verbose_name="fecha registro", auto_now_add=True,)

    class Meta:
        ordering = ['ticket']
        verbose_name = 'AuditoriaTicketEstado'
        verbose_name_plural = 'AuditoriaTicketEstado'

    def __str__(self):
        return str(self.pk)
#===============================================================================
class Observacion(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.PROTECT)
    registro = models.CharField(max_length=1024, blank=True)
    f_registro = models.DateTimeField(verbose_name="fecha registro", auto_now_add=True,)
    class Meta:
        ordering = ['ticket']
        verbose_name = 'ObservacionTicket'
        verbose_name_plural = 'ObservacionesTicket'

    def __str__(self):
        return str(self.pk)

apps/tickets/views.py
import json
from config.utils import render_to_pdf
from datetime import datetime, timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse
from django.views.generic import ListView, View
from django.views.generic.edit import CreateView, UpdateView, FormView, DeleteView
from .functions import getPaginatorItems
from .forms_ticket import (TicketUpdateForm)
from .models import *


# # Create your views here.
# @login_required(login_url='login')
# def index(request):
#     return render(request, 'tickets/index.html', {'usuario': request.user })

class Tickets(ListView):
    model = Ticket
    context_object_name = 'tickets'
    template_name = 'tickets/list.html'
    paginate_by = 10
    def get_queryset(self): #Uso el filtro para que según el usuario vea:
        user = self.request.user
        if user.groups.filter(name__in=['Tecnicos']).exists():#SI ES TECNICO SOLO LOS CASOS QUE TIENE
            object_list = Ticket.objects.filter( Q(responsable=user) | Q(solicitante=user) ).exclude(estado=EstadoTicket.objects.get(id=50)).exclude( estado=EstadoTicket.objects.get(id=70))
            try:
                busqueda = self.request.GET['buscar']
            except:
                busqueda = ''
            if(busqueda !=''):
                object_list = object_list.filter(nombre__icontains = busqueda) \
                    | object_list.filter(descripcion__icontains = busqueda)

            return object_list

        elif user.groups.filter(name__in=['Administradores']).exists():#SI ES EL SUPERVISOR TODOS
            object_list = Ticket.objects.all()
            try:
                busqueda = self.request.GET['buscar']
            except:
                busqueda = ''
            if(busqueda !=''):
                object_list = object_list.filter(nombre__icontains = busqueda) \
                    | object_list.filter(descripcion__icontains = busqueda)

            return object_list

        elif user.groups.filter(name__in=['Supervisor']).exists():#SI ES EL SUPERVISOR TODOS
            object_list = Ticket.objects.all()
            try:
                busqueda = self.request.GET['buscar']
            except:
                busqueda = ''
            if(busqueda !=''):
                object_list = object_list.filter(nombre__icontains = busqueda) \
                    | object_list.filter(descripcion__icontains = busqueda)

            return object_list

        elif user.groups.filter(name__in=['Usuarios']).exists():#SI ES EL USUARIO solo LO QUE HAYA ABIERTO
            object_list = Ticket.objects.filter(solicitante=user)
            try:
                busqueda = self.request.GET['buscar']
            except:

                busqueda = ''
            if(busqueda !=''):
                object_list = object_list.filter(nombre__icontains = busqueda) \
                    | object_list.filter(descripcion__icontains = busqueda)
            return object_list
        else:
            object_list = []
            return object_list

    def get_context_data(self, **kwargs):
        # print ("===============================================================")
        # print ("kwargs: ", **kwargs )
        # print ("===============================================================")
        context = super(Tickets, self).get_context_data(**kwargs)
        # print ("===============================================================")
        # print ("Paso de la instancia de la clase superior en get context " )
        # print ("===============================================================")
        if not context.get('is_paginated', False):
            try:
                busqueda = self.request.GET['buscar']
                print("encontro buscar...", busqueda)
            except:
                busqueda = ''
            context.update({'busqueda':busqueda})
            return context

        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        try:
            busqueda = self.request.GET['buscar']
            print("encontro buscar...", busqueda)
        except:
            busqueda = ''
        current_page = context.get('page_obj')
        page_no = current_page.number
        if num_pages <= 8 or page_no <= 5:  # case 1 and 2
            pages = [x for x in range(1, min(num_pages + 1, 9))]
        elif page_no > num_pages - 4:  # case 4
            pages = [x for x in range(num_pages - 5, num_pages + 1)]
        else:  # case 3
            pages = [x for x in range(page_no - 3, page_no + 3)]
        context.update({'pages': pages, 'busqueda':busqueda})
        return context

class TicketCreate( LoginRequiredMixin, CreateView):
    model = Ticket
    fields = '__all__'
    template_name = 'tickets/create.html'

    def form_valid(self, form):
        user = self.request.user
        if form.instance.estado==None:
            form.instance.estado= EstadoTicket.objects.get(id=10)
        form.instance.solicitante = user
        return super().form_valid(form)
    def get_success_url(self):
        ticket= Ticket.objects.get(pk=self.object.id)
        auditoria = AuditoriaTicketEstado(ticket=ticket, estado=EstadoTicket.objects.get(id=10), usuario=self.request.user,
                    usuario_responsable=ticket.responsable, observaciones=ticket.descripcion )
        auditoria.save()
        return reverse('tickets')


class TicketUpdate(UpdateView): #Funciona  para asignar un Ticket a un  responsable
    model = Ticket
    form_class = TicketUpdateForm
    template_name = 'tickets/update.html'
    success_url = '/ticket'
    def form_valid(self, form):
        print(" Se añadio responsable ")
        form.instance.estado= EstadoTicket.objects.get(id=20) #el ticket se pasa a "asignado"
        ticket= Ticket.objects.get(pk=self.object.id)
        auditoria = AuditoriaTicketEstado(ticket=ticket, estado=EstadoTicket.objects.get(id=20), usuario=self.request.user,
                    usuario_responsable=self.object.responsable, observaciones=form.instance.notas )
        auditoria.save()
        return super().form_valid(form)
    def get_context_data(self, **kwargs): # Paso ambos contextos
        context = super(TicketUpdate, self).get_context_data(**kwargs)
        context['observaciones'] = Observacion.objects.filter(ticket=self.object.id)
        return context

class TicketReasignado(UpdateView):
    model = Ticket
    fields = '__all__'
    template_name = 'tickets/update.html'
    success_url= '/ticket'

class TicketDelete(DeleteView):
    model = Ticket
    template_name = 'tickets/delete.html'

class GeneratePDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('tickets/pdfview.html')
        context = {
            "cliente_name": "Andres Garcia ", #Nombre del cliente
            "cliente_tel": "3166128479 ", #tel del cliente
            "cliente_email": "andres@grupoda.com ", #email del cliente
            "fecha_factura": date.today(),          #fecha de la facturacion
            "cuerpo_mensaje":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "cuerpo_notas":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "nombre_asesor":"Yineth Vergara",
            "valor_subtotal": "100",
            "valor_iva":"19",
            "valor_Total":"119"
        }
        # html = template.render(context)
        pdf = render_to_pdf('tickets/pdfview.html', context)
        if pdf:
            return HttpResponse(pdf, content_type='application/pdf')
        return HttpResponse("Archivo no encontrado")
        # return HttpResponse(html)

class TicketGestion(View): #esta funcion hace todos los cambios de estado de tickets
    def get(self, request, *args, **kwargs):
        estado = request.GET['estado_id']
        ticket = Ticket.objects.get(pk=request.GET['id'])
        if request.is_ajax():
            if estado == 'ASIGNADO': #Asignado PAso a Aceptado
                ticket.estado=EstadoTicket.objects.get(id=30)
                nuevo_estado = "Aceptado"
                ticket.save()
            if estado == 'ACEPTADO': #ACEPTADO PAso a EN EJECUCION Toma tiempo inicio
                ticket.estado=EstadoTicket.objects.get(id=40)
                ticket.f_inicio= datetime.now(timezone.utc)
                nuevo_estado = "En ejecución"
                ticket.save()
            if estado == 'EN_EVALUACION': #Pasa a en evaluacion si se soluciono
                ticket.estado=EstadoTicket.objects.get(id=50)
                ticket.solucion=request.GET['mensaje']
                nuevo_estado = request.GET['mensaje']
                ticket.save()
            if estado == 'NO_CONCLUIDO': #pasa ene valuacion si no se pudo solucionar
                ticket.estado=EstadoTicket.objects.get(id=80)
                ticket.solucion=request.GET['mensaje']
                nuevo_estado = request.GET['mensaje']
                ticket.save()
            if estado == 'FINALIZADO': #SI SE SOLUCIONO
                ticket.estado=EstadoTicket.objects.get(id=70)
                ticket.retroalimentacion = request.GET['mensaje']
                ticket.calificacion = request.GET['calificacion']
                ticket.f_fin= datetime.now(timezone.utc)
                nuevo_estado = request.GET['mensaje']
                ticket.save()

apps/tickets/templates/sidebar.html
{% load i18n static %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{% static 'adminlte/assets/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% static 'adminlte/assets/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{user.username}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <!-- modulo de administrador.........                   ---------->
        {% if request.user.is_staff %}
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              ADMINISTRAR..
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href= "{% url 'tickets' %}" class="nav-link active">
                <i class="far fa-circle nav-icon"></i>
                <p>Nuevo Usuario</p>
              </a>
            </li>
            <li class="nav-item">
              <a href= "{% url 'ticket-create' %}" class="nav-link active">
                <i class="far fa-circle nav-icon"></i>
                <p>Otros ajustes</p>
              </a>
            </li>

          </ul>
        </li>
        {% endif %}
        <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         ------------>
        <li class="nav-item has-treeview ">
          <a href="#" class="nav-link">
            <i class="fas fa-hands-helping"></i>
            <p>
              Mesa de ayuda
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href= "{% url 'tickets' %}" class="nav-link">
                <i class="fas fa-list-ol"></i>
                <p>Mis Solicitudes</p>
              </a>
            </li>
            {% if perms.tickets.add_ticket %}
            <li class="nav-item">
              <a href= "{% url 'ticket-create' %}" class="nav-link">
                <i class="fas fa-external-link-alt"></i>
                <p>Nueva Orden Mantto</p>
              </a>
            </li>
            {% endif %}

            
            <!-- {% if perms.tickets.add_ticket %}
            <li class="nav-item">
                <p>Puede adicionar ticket</p>
            </li>
            {% endif %}
            {% if perms.tickets.change_ticket %}
            <li class="nav-item">
                <p>Puede cambiar ticket</p>
            </li>
            {% endif %}
            {% if perms.tickets.delete_ticket %}
            <li class="nav-item">
                <p>Puede borrar  ticket</p>
            </li>
            {% endif %}
            {% if perms.tickets.view_ticket %}
            <li class="nav-item">
                <p>Puede visualizar  ticket</p>
            </li>
            {% endif %} -->

          </ul>
        </li>
        <!-- <li class="nav-item">
          <a href="pages/widgets.html" class="nav-link">
            <i class="nav-icon fas fa-th"></i>
            <p>
              Widgets
              <span class="right badge badge-danger">New</span>
            </p>
          </a>
        </li> -->
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>