apps/campeonato/urls.py
from django.urls import include, path
from . import views
from apps.campeonato import views

urlpatterns = [
    # URLS de Usuario Administrador Equipos
    path('',                                        views.IndexView.as_view(),                  name='index'),
    path('mis-equipos/',                            views.EquipoList.as_view(),                 name='equipo-list'),
    path('evento/<int:pk>/inscribirme',             views.EquipoCreate.as_view(),               name='equipo-create'),
    path('planilla/departamento/municipio/list/',   views.MunicipiosDepartamento.as_view(),     name='depto-municipios'),
    path('equipo/<int:pk>/integrantes/',            views.IntegranteList.as_view(),             name='integrante-list'),
    path('equipo/jugador/update/<int:pk>',          views.IntegranteUpdate.as_view(),           name='integrante-update'),
    path('equipo/jugador/delete/<int:pk>',          views.IntegranteDelete.as_view(),           name='integrante-delete'),
    path('equipo/tecnico/update/<int:pk>',          views.TecnicoUpdate.as_view(),              name='tecnico-update'),
    path('equipo/tecnico/delete/<int:pk>',          views.TecnicoDelete.as_view(),              name='tecnico-delete'),
    path('equipo/<int:pk>/actualizar-info',         views.EquipoUpdate.as_view(),               name='equipo-update'),
    path('equipo/<int:pk>/borrar',                  views.EquipoDelete.as_view(),               name='equipo-delete'),

    #URLs de Usuario Administrador de Eventos
    path('evento/<int:pk>/',                    views.AdminFaseInicial.as_view(),                   name="campeonato" ),
    path('verintegrantes/',                     views.VerIntegrantes.as_view(),                     name="ver-integrantes" ),
    path('aprobar-equipo',                      views.AprobarEquipo.as_view(),                      name='aprobar-equipo'),
    path('rechazar-equipo',                     views.RechazarEquipo.as_view(),                     name='rechazar-equipo'),
    path('categoria/grupos/recomendacion',      views.RecomendacionGrupos.as_view(),                name='recomendacion-grupos'),
    path('equipos/grupos/manual',               views.EquiposGrupoManual.as_view(),                 name="equipos-grupo-manual"),
    path('categoria/generacion/grupos/auto',    views.CategoriaGenerarGruposAutomatico.as_view(),   name="grupos-auto"),
    path('categoria/sorteo/liguilla',           views.CategoriaGenerarLiguilla.as_view(),           name="categoria-generar-liguilla"),
    path('categoria/generacion/grupos/manual',  views.CategoriaGenerarGruposManual.as_view(),       name="grupos-manual"),
    path('categoria/grupos/ver',                views.VerDistribucionGrupos.as_view(),              name='ver-grupos'),
    path('categoria/partidos/generar',          views.PartidoGenerar.as_view(),                     name='partidos-generar'),
    path('categoria/fase/partidos',             views.FasePartidos.as_view(),                       name="fase-partidos"),
    path('categoria/fases',                     views.CategoriaFases.as_view(),                     name="categoria-fases"),

    path('partido/datos-consulta',              views.PartidoConsultaDatos.as_view(),               name='partido-datos-consulta'),
    path('equipos/jugadores/list/',             views.JugadoresEquipos.as_view(),                   name='equipos-jugadores'),
    path('planilla/equipos/jugadores/list',     views.PartidoJugadoresEquiposVer.as_view(),         name='partido-equipos-jugadores'),
    path('partidos/validar-clasificacion',      views.PartidoValidarClasificacion.as_view(),        name='partidos-validar-clasificacion'),
    path('partido/diligenciar',                 views.PartidoEdit.as_view(),                        name='partido-edit'),

    path('clasificacion/categoria',             views.ClasificacionCategoria.as_view(),             name='clasificacion-categoria'),

    path('estadisticas/categoria/equipos',      views.EstadisticasCategoriaEquipos.as_view(),       name='estadisticas-categoria-equipos'),
    path('estadisticas/categoria/jugadores',    views.EstadisticasCategoriaJugadores.as_view(),     name='estadisticas-jugadores'),




# RECICLADO
    # path('evento/<int:pk>/partidos/sorteo',                          views.PartidosGenerate.as_view(),      name='partido-generate'),
    # path('evento/<int:pk>/partidos/fixture',                         views.PartidoListView.as_view(),       name='partido-list-view'),
    # path('evento/<int:pk>/partidos/diligenciar',                     views.PartidoListEdit.as_view(),       name='partido-list-edit'),
    # path('partidos/detalle/planilla-<int:pk>',       views.PartidoListDetail.as_view(),     name='partido-list-detail'),
    # path('categoria/equipos/list/',   views.EquiposCategoria.as_view(),   name='categoria_equipos'),
    # path('partido/jugadores/list/<int:pk>/',   views.JugadoresPartidoList.as_view(),   name='jugadores-partido-list'),
    # path('partido/delete/<int:pk>',            views.PartidoDelete.as_view(),          name='partido-delete'),
    # path('evento/<int:pk>/clasificacion/ver',                   views.Clasificacion.as_view(),         name='clasificacion'),
    # path('evento/<int:pk>/estadisticas/equipos', views.EstadisticasEquipos.as_view(), name='estadisticas-equipos'),
    # path('evento/<int:pk>/estadisticas/jugadores', views.EstadisticasJugadores.as_view(), name='estadisticas-categoria-jugadores'),
    # # path('estadisticas/categoria', views.EstadisticasCategoria.as_view(), name='estadisticas-categoria'),
    # path('clasificacion/',  views.ClasificacionView.as_view(),  name='clas'),
    # path('equipo/estado',   views.EquipoEstado.as_view(),            name='equipo-estado'),
    # path('planilla/integrante/create/',          views.IntegranteCreate.as_view(),  name='integrante-create'),
    # path('evento/<int:pk>/equipos/',    views.AdminEquiposList.as_view(),    name="equipos-list" ),
    # path('evento/<int:pk>/jugadores/',  views.AdminJugadoresList.as_view(),  name="jugadores-list" ),
    # path('evento/<int:pk>/tecnicos/',   views.AdminTecnicosList.as_view(),   name="tecnicos-list" ),
    # path('versaldo/',        views.VerSaldo.as_view(),        name="ver-saldo" ),
    # path('evento/<int:pk>/grupos/ver',                 views.GruposView.as_view(),          name="grupos"),
    # path('evento/<int:pk>/grupos/sorteo',           views.GruposCreateView.as_view(),    name='grupos-sorteo'),
    # # path('categoria/sorteo/grupos',        views.CategoriaGenerarGrupos.as_view(),     name="grupos-categoria"),
    # path('grupos/categoria/list',   views.GruposCreadosView.as_view(),   name="grupos-categoria-list"),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.admin2.urls')),
    path('', include('apps.contactos.urls')),
    path('', include('apps.tickets.urls')),
    path('', include('apps.campeonato.urls')),
    path('', include('apps.evento.urls')),
]

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/campeonato/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls.base import reverse
from typing import Any

from apps.contactos.models import Contacto, Departamento, Municipio
from apps.evento.models import Categoria, Evento

class JugadoresPartido(models.Model):
    jugador = models.ForeignKey(Contacto, models.DO_NOTHING)
    gol_partido = models.IntegerField(blank=True, null=True)
    amarilla_partido = models.IntegerField(blank=True, null=True)
    roja_partido = models.IntegerField(blank=True, null=True)
    numero = models.IntegerField(blank=True, null=True)
    local = models.BooleanField(default=True)
    evento = models.ForeignKey(Evento, models.DO_NOTHING)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Jugador_Partido'
        verbose_name_plural = 'Jugadores_Partido'

    def __str__(self):
        return "{}".format(self.jugador)

class Equipo(models.Model):
    nombre = models.CharField(max_length=512)
    categoria = models.ForeignKey(Categoria, models.DO_NOTHING, blank=True, null=True)
    municipio = models.ForeignKey(Municipio, models.DO_NOTHING, blank=True, null=True)
    departamento = models.ForeignKey(Departamento, models.DO_NOTHING, blank=True, null=True)
    observaciones = models.TextField(default="", blank=True, null=True)
    creado_por = models.ForeignKey(User, models.DO_NOTHING, blank=True, null=True, related_name="equipo_creado_por")
    abono_inscripcion=models.PositiveIntegerField(blank=True, null=True ,default=0)
    saldo_inscripcion = models.PositiveIntegerField(blank=True, null=True ,default=1500000)
    activo = models.BooleanField(blank=True, default=True)
    aprobado = models.BooleanField(blank=True, null=True)
    evento = models.ForeignKey(Evento, models.DO_NOTHING)

    def obtener_jugadores_equipo(self):
        return Contacto.objects.filter(equipo=self, es_jugador=True)

    def obtener_cuerpo_tecnico_equipo(self):
        return Contacto.objects.filter(equipo=self, es_jugador=False)

    def __str__(self):
        return '{}'.format(self.nombre)

class Abono(models.Model):
    equipo = models.ForeignKey(Equipo, models.DO_NOTHING)
    valor = models.PositiveIntegerField()
    fecha = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    archivo = models.FileField(upload_to='static/campeonato', blank=True, null=True)
    evento = models.ForeignKey(Evento, models.DO_NOTHING)

    def __str__(self):
        return '{} {}'.format(self.equipo, self.valor)

    class Meta:
        ordering = ['id']
        verbose_name = 'Abono'
        verbose_name_plural = 'Abonos'

class Grupo(models.Model):
    nombre = models.CharField(max_length=512)
    categoria = models.ForeignKey(Categoria, models.CASCADE)
    equipos = models.ManyToManyField(Equipo, related_name="Integrantes")
    numero_equipos = models.PositiveIntegerField(default=0)
    numero_clasificados = models.PositiveIntegerField(default=2)
    equipos_clasificados = models.ManyToManyField(Equipo, related_name="Clasificados")
    evento = models.ForeignKey(Evento, models.DO_NOTHING)
    numero_rondas = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ['id']
        verbose_name = 'Grupo'
        verbose_name_plural = 'Grupos'

    def __str__(self):
        return " {} Grupo {}".format(self.categoria, self.pk)

class Partido(models.Model):
    numero_partido = models.PositiveIntegerField(blank=True, null=True)
    fase = models.CharField(max_length=512, blank=True, null=True)
    categoria = models.ForeignKey(Categoria, models.DO_NOTHING)
    local = models.ForeignKey(Equipo, models.DO_NOTHING, related_name="Equipo_Local")
    visitante = models.ForeignKey(Equipo, models.DO_NOTHING, related_name="Equipo_Visitante")
    arbitro1 = models.CharField(max_length=512, blank=True, null=True)
    arbitro2= models.CharField(max_length=512, blank=True, null=True)
    arbitro3= models.CharField(max_length=512, blank=True, null=True)
    cronogramista = models.CharField(max_length=512, blank=True, null=True)
    coordinador = models.CharField(max_length=512, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    ganador = models.ForeignKey(Equipo, models.DO_NOTHING, blank=True, null=True, related_name="Equipo_Ganador")
    jugadores = models.ManyToManyField(JugadoresPartido)
    soporte = models.FileField(upload_to='static/planillas', blank=True, null=True)
    grupo = models.ForeignKey(Grupo, models.DO_NOTHING, blank=True, null=True)
    estado = models.BooleanField(default=False)
    evento = models.ForeignKey(Evento, models.DO_NOTHING)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Partido'
        verbose_name_plural = 'Partidos'

    def __str__(self):
        return "{} {}".format(self.categoria, self.numero_partido)

class ActivarClasificados(models.Model):
    fase = models.CharField(max_length=512, blank=True, null=True)
    activar = models.BooleanField(default=False)

apps/campeonato/forms.py
from django import forms
from .models import Partido, Abono

class PartidoForm(forms.ModelForm):
    class Meta:
        model = Partido
        fields = '__all__'

class AbonoForm(forms.ModelForm):
    class Meta:
        model = Abono
        fields = ['equipo', 'valor', 'archivo']

apps/campeonato/templates/equipo/list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block extracss %}{% endblock %}
{% block content %}
 <!--  BEGIN MAIN CONTAINER  -->
 <div class="main-container" id="container">
    <div class="overlay"></div>
    <div class="ps-overlay"></div>
    <div class="search-overlay"></div>



    <!--  BEGIN CONTENT PART  -->
    <div id="content" class="main-content">
        <div class="container">
            <div class="page-header">
                <div class="page-title">
                    <h3>{{nombre_evento}}</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-xl-12 col-lg-12 col-12 layout-spacing">
                    <div class="statbox widget box box-shadow">
                        <section class="content">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-10">
                            <h1 class="mb-2">Mis Equipos</h1>
                        </div>
                    </div>
                </div>
        </div>
        <div class="content-header">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-6">
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="javascript:history.back()"">Evento</a></li>
                        <li class="breadcrumb-item"><a href="">Nuevo Equipo</a></li>
                    </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10">
                        <div class="card">
                            <div class="card-body">
                                <div class="card-columns">
                                    {% for equipo in equipos %}
                                        <div class="card">
                                            <div class="card-header border-0 ui-sortable-handle" style="cursor: move;">
                                                <div class="card-title text-center">
                                                    <b style="margin-left: 15px;">{{equipo.nombre}}</b>
                                                </div>
                                                <div class="card-tools">
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-default btn-sm dropdown-toggle border-0" data-toggle="dropdown" data-offset="-52" aria-expanded="false">
                                                            <i class="fas fa-bars"></i>
                                                        </button>
                                                        <div class="dropdown-menu text-center" role="menu" style="position: absolute; transform: translate3d(-52px, 31px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                            
                                                            <a class="dropdown-item" href="{% url 'integrante-list' equipo.pk %}">
                                                                Ver <i class="fas fa-list-ol"></i>
                                                            </a>
                                                            <a class="dropdown-item" href="{% url 'equipo-update' equipo.pk %}">
                                                                Editar <i class="fas fa-pencil-alt"></i>
                                                            </a>
                                                            <a class="dropdown-item" href="{% url 'equipo-delete' equipo.pk %}">
                                                                Borrar <i class="fas fa-trash"></i>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-body text-center">
                                                <div class="row">
                                                    <div class="col-8">
                                                        <p>{{equipo.evento.nombre}}</p>
                                                        <p>{{equipo.categoria}}</p>
                                                    </div>
                                                    <div class="col-4">
                                                        {% if equipo.evento.disciplina.pk == 1 %}
                                                        <i class="fas fa-futbol fa-3x"></i>
                                                        {% elif equipo.evento.disciplina.pk == 2 %}
                                                        <i class="fas fa-basketball-ball fa-4x"></i>
                                                        {% elif equipo.evento.disciplina.pk == 3 %}
                                                        <i class="fas fa-volleyball-ball fa-4x"></i>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="card">
                            <div class="card-header text-center">
                                <b>Filtros</b>
                            </div>
                            <div class="card-body">
                                <div class="btn-group-vertical">
                                    <button type="button" class="btn btn-default">Todos</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block page_js_level %}
{% endblock %}

apps/campeonato/templates/equipo/update.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block extracss %}{% endblock %}
{% block content %}

<div class="content-wrapper">
  <section class="content">
    <div class="content-header">
        <div class="jumbotron">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-10">
                        <h1 class="display-4">Informacion del Equipo</h1>
                    </div>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div><!-- /.col -->
                <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:history.back()">Equipo</a></li>
                    <li class="breadcrumb-item"><a href="">Informacion</a></li>
                </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="card">
            <form name='equipo' class="form-horizontal needs-validation" method="post" action="{% url 'equipo-update' equipo.pk %}" enctype="multipart/form-data">
              {% csrf_token %}
                  <div class="card-body">
                    <div class="tab-content">
                      <div class="tab-pane active" id="tab_1">
                        <div class="row">
                          <div class="col-6">
                            <div class="form-group">
                              <label for="nombre">Nombre Equipo:</label>
                              {% render_field form.nombre class="form-control" placeholder="Nombre" data-toggle="tooltip" data-placement="top" title="Nombres" %}
                              {% for error in form.nombre.errors %}
                                <p class="text-danger">{{ error }}</p>
                              {% endfor %}
                            </div>
                          </div>
                          <div class="col-6" id="selectcat">
                            <div class="form-group">
                              <label for="firstName">Categoria: </label>
                              {% render_field form.categoria class="form-control" placeholder="Nombre" data-toggle="tooltip" data-placement="top" title="Nombres" %}
                              {% for error in form.categoria.errors %}
                                <p class="text-danger">{{ error }}</p>
                              {% endfor %}
                              
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-6">
                            <div class="form-group">
                              <label for="firstName">Departamento: </label>
                              {% render_field form.departamento class="form-control" placeholder="Nombre" data-toggle="tooltip" data-placement="top" title="Nombres" %}
                              {% for error in form.departamento.errors %}
                                <p class="text-danger">{{ error }}</p>
                              {% endfor %}
                            </div>
                          </div>
                          <div class="col-6">
                            <div class="form-group">
                              <label for="firstName">Municipio: </label>
                              {% render_field form.municipio class="form-control" placeholder="Nombre" data-toggle="tooltip" data-placement="top" title="Nombres" %}
                              {% for error in form.municipio.errors %}
                                <p class="text-danger">{{ error }}</p>
                              {% endfor %}
                            </div>
                          </div>
                        </div>
                        <button id="btn-siguiente" name="siguiente" class="btn btn-default" type="submit">Actualizar</button>
                        <a class="btn btn-default"  href="{% url 'equipo-list' %}">Volver</a>  
                      </div>
                    </div>
                  </div><!-- /.card-body -->
                </form>
              </div>
              <!-- ./card -->
            </div>
            <!-- /.col -->
          </div>
        </div>

  <!-- /.content -->
    </section>
  <!-- #header-content-wrapper -->
</div>
{% endblock %}

{% block page_js_level %}

<!-- Parsley -->
<script type="text/javascript">

    //===============================================================================================================================
    //____________________________          TAB 1        ____________________________________________________________________________
    
    // CON ESTAS LINEAS SE CONSULTA CADA VEZ QUE ESTOS CAMPOS CAMBIEN QUITEN LA OPCION  INVALIDA
    $("#id_categoria").change(function(){
      $('#id_categoria').removeClass('is-invalid');
    });
    
    $("#id_municipio").change(function(){
      $('#id_municipio').removeClass('is-invalid');
    });
    
    $("#nombre_equipo").change(function(){
      $('#nombre_equipo').removeClass('is-invalid');
    });
    
    // Funcion que modifica las opciones del select de municipios de acuerdo al select de departamento
    $("#id_departamento").change(function(){
        $('#id_departamento').removeClass('is-invalid');
       // alert("Si cambio");
        var deptoSeleccionado = $(this).children("option:selected").val();
       // alert("la almacend fue......" + zonaSeleccionado);
        const url = '/planilla/departamento/municipio/list/';  //esta es la url donde voy  a consultar
        $("#id_municipio").empty();
        $("#id_municipio").append("<option value='0'>Seleccione</option>");
      
        if (deptoSeleccionado != ''){
          $.get(url, {"depto_pk": deptoSeleccionado }, function(data,status){
            if (status=="success"){
              var resultados = data['municipios'];
              console.log('Resultados'+resultados)
              for (i=0; i<resultados.length; i++){
                var resultado = resultados[i];
                $('#id_municipio').append("<option value='"+resultado["pk"]+"'>"+resultado["nombre"]+"</option>").trigger("chosen:updated");
              }
            }
            else{
              alert("no se logra conectar al servidor");
            }
          });
        }
    });
    
    //VALIDAMOS LOS CAMPOS DEL TAB1
    function validar_tab1(){
      var equipo_nombre = document.getElementById('nombre_equipo');
      var categoria_select = document.getElementById('id_categoria');
      var departamento_select = document.getElementById('id_departamento');
      var municipio_select = document.getElementById('id_municipio');
    
      let selects  = [[categoria_select,'#id_categoria'],[departamento_select,'#id_departamento'],[municipio_select,'#id_municipio']];
      var validado = true;
    
      var nombre =equipo_nombre.value;
      if (nombre == ""){
        validado = false;
        $('#nombre_equipo').addClass('is-invalid');
      }
      for (let j=0; j < selects.length; j++){
        //console.log("evalua el select"+(j+1));
        var opcion = selects[j][0].value;
        //console.log("la opcion del select "+(j+1)+"es "+opcion);
        if (opcion=='0'){
    
          //console.log("opcion es igual a 0");
          //console.log("viene con el estado valido"+validado);
          $(selects[j][1]).addClass('is-invalid');
          if (validado == true){
            validado = false;
          }
          else{
            validado = false;
          }
        }
        
      }
      //console.log("retorna esto "+validado);  
      return validado;
      //return true;
    }
    
    
    // CON EL BTN SIGUIENTE SE EFECTUA LA VALIDACION DE TODOS LOS CAMPOS, SI ESTAN BIEN SE CAMBIA DE TAB Y SE ACTIVA EL BTN DE JUGADORES
    const btn_siguiente = document.getElementById('btn-siguiente');
    $()
    
    btn_siguiente.addEventListener('click', () => {
    
    
      if (validar_tab1() == true){
        $("#btn-siguiente").removeAttr("style");
      }
    });
    
</script>
    
{% endblock %}